/**
 * Provider ports (BUILD_PLAN.md §5.2). Small capabilities instead of one all-purpose connector.
 * Adapters implement only what their provider supports; the engine never falls back to another
 * adapter or channel when a capability is missing.
 */
import type { CapabilitySnapshot, ProviderPurpose } from './capabilities';
import type { ErrorClass } from './errors';

export interface SenderIdentity {
  readonly name: string;
  readonly address: string;
  readonly organization?: string;
  readonly postalAddress?: string;
  readonly replyTo?: string;
}

export interface ProviderAccountRef {
  readonly id: string;
  readonly provider: string;
  readonly externalAccountId: string;
  readonly sender: SenderIdentity;
}

/** Resolves a secret reference ("env:NAME", "keychain:NAME") at call time. Values are never stored. */
export interface SecretResolver {
  get(ref: string): Promise<string>;
  /**
   * Replaces a secret's value, for credentials the provider rotates (Microsoft refresh tokens). Optional:
   * resolvers that cannot write (environment variables) omit it, and callers must cope.
   */
  put?(ref: string, value: string): Promise<void>;
}

export interface ProviderContext {
  readonly workspaceId: string;
  readonly account: ProviderAccountRef;
  readonly secretRef: string;
  readonly secrets: SecretResolver;
  readonly traceId: string;
  readonly signal: AbortSignal;
  readonly now: () => number;
}

/**
 * Supplies OAuth access tokens to adapters that act as a mailbox user. The grant may be held by the engine
 * (a refresh token behind `secretRef`) or by a host, such as Papr's planned server-side connectors
 * (BUILD_PLAN.md §19 D1). Adapters never see how the token was obtained.
 */
export interface AccessTokenSource {
  get(ctx: ProviderContext): Promise<string>;
  /** Called after the provider rejects a token (HTTP 401), so the next `get` fetches a fresh one. */
  invalidate(ctx: ProviderContext): void;
}

/** A token could not be obtained; `errorClass` says whether reconnecting the account is needed. */
export class TokenError extends Error {
  constructor(
    readonly errorClass: ErrorClass,
    message: string,
  ) {
    super(message);
    this.name = 'TokenError';
  }
}

export type AccountHealth = 'ok' | 'degraded' | 'unhealthy' | 'reauth_required';

export interface AccountPort {
  discover(ctx: ProviderContext): Promise<CapabilitySnapshot>;
  health(ctx: ProviderContext): Promise<{ status: AccountHealth; detail?: string }>;
}

export interface EmailAddress {
  readonly address: string;
  readonly name?: string;
}

export interface EmailContent {
  readonly from: EmailAddress;
  readonly to: readonly EmailAddress[];
  readonly replyTo?: EmailAddress;
  readonly subject: string;
  readonly text: string;
  readonly html?: string;
  readonly headers: Readonly<Record<string, string>>;
  readonly inReplyTo?: string;
  readonly references?: readonly string[];
  readonly providerThreadId?: string;
}

export interface ApprovedEmail extends EmailContent {
  readonly actionId: string;
  readonly idempotencyKey: string;
  /** Generated by the engine; used for reply correlation and reconciliation. */
  readonly rfcMessageId: string;
  readonly contentHash: string;
}

export interface UncertainEmail {
  readonly actionId: string;
  readonly idempotencyKey: string;
  readonly rfcMessageId: string;
  readonly to: readonly string[];
  readonly attemptedAt: number;
}

export interface ProviderReceipt {
  readonly providerMessageId: string;
  readonly providerThreadId?: string;
  readonly rfcMessageId?: string;
  readonly acceptedAt: number;
  /** Identifiers only. Never bodies, tokens or credentials. */
  readonly raw?: Readonly<Record<string, string>>;
}

export type SendResult =
  | { readonly kind: 'accepted'; readonly receipt: ProviderReceipt }
  | {
      readonly kind: 'rejected';
      readonly errorClass: ErrorClass;
      readonly retryAfterMs?: number;
      readonly detail: string;
    }
  /** The request may have reached the provider (timeout, reset after send). Never retried blindly. */
  | { readonly kind: 'unknown'; readonly detail: string };

export type ReconcileResult =
  | { readonly kind: 'found'; readonly receipt: ProviderReceipt }
  /** Only when the provider can affirm the message was not sent. */
  | { readonly kind: 'absent' }
  | { readonly kind: 'still_unknown'; readonly detail: string };

export interface EmailSender {
  send(ctx: ProviderContext, email: ApprovedEmail): Promise<SendResult>;
  reconcile(ctx: ProviderContext, email: UncertainEmail): Promise<ReconcileResult>;
}

export type InboundKind = 'message' | 'bounce' | 'complaint' | 'delivery';

export interface InboundMailEvent {
  /** Stable provider event id, used for deduplication across webhook retries and poll overlap. */
  readonly eventId: string;
  readonly kind: InboundKind;
  readonly providerMessageId: string;
  readonly providerThreadId?: string;
  readonly rfcMessageId?: string;
  readonly inReplyTo?: string;
  readonly references: readonly string[];
  readonly from: string;
  readonly to: readonly string[];
  readonly subject?: string;
  readonly receivedAt: number;
  readonly headers: Readonly<Record<string, string>>;
  readonly contentType?: string;
  /** Delivery status notification details for bounces. */
  readonly dsn?: { readonly status: string; readonly recipient?: string; readonly originalMessageId?: string };
  /** At most 500 characters, used only for deterministic classification. */
  readonly snippet?: string;
}

export interface MailboxReader {
  readChanges(
    ctx: ProviderContext,
    cursor: string | null,
  ): Promise<{ events: readonly InboundMailEvent[]; nextCursor: string }>;
}

export interface WebhookVerifier {
  /** Verify over the raw body BEFORE parsing. Returns 'reject' on bad signature, stale timestamp or oversize body. */
  verify(
    rawBody: Uint8Array,
    headers: Readonly<Record<string, string>>,
    secret: string,
    now: number,
  ): Promise<readonly InboundMailEvent[] | 'reject'>;
}

export interface Notification {
  readonly title: string;
  readonly lines: readonly string[];
  readonly severity: 'info' | 'warning' | 'error';
  readonly link?: string;
}

export interface NotificationPublisher {
  publish(ctx: ProviderContext, notification: Notification & { idempotencyKey: string }): Promise<SendResult>;
}

export interface ManualTaskInput {
  readonly taskId: string;
  readonly channel: string;
  readonly targetUrl?: string;
  readonly draft: string;
}

/** Hosts may announce manual tasks (e.g. open a URL for the human). Completing a task is always a human action. */
export interface ManualTaskProvider {
  prepare(ctx: ProviderContext, input: ManualTaskInput): Promise<void>;
}

/** Everything one provider integration offers. Missing ports mean "unsupported", never "fall back". */
export interface ProviderAdapter {
  readonly name: string;
  /** Purposes the provider's terms permit. */
  readonly purposes: readonly ProviderPurpose[];
  readonly account: AccountPort;
  readonly email?: EmailSender;
  readonly mailbox?: MailboxReader;
  readonly webhook?: WebhookVerifier;
  readonly notify?: NotificationPublisher;
  readonly manual?: ManualTaskProvider;
}
