import {
  VERIFICATION_ADAPTER_CONTRACT_VERSION,
  defineProviderManifest,
  plainStringProperty,
  secretStringProperty,
  type ProviderManifestV1,
} from '@splitin/verification-adapter-sdk';

export const personaProviderManifest: Readonly<ProviderManifestV1> = defineProviderManifest({
  contractVersion: VERIFICATION_ADAPTER_CONTRACT_VERSION,
  adapterVersion: '1.0.0',
  engineCompatibility: '1.0.0',
  provider: 'persona',
  displayName: 'Persona',
  description: 'Persona identity verification: human IDV, business KYB, associated people, and ownership review. Documents remain at Persona; adapters return opaque evidence references only.',
  supportedPackages: ['human_idv', 'business_kyb', 'associated_person_idv', 'ownership_review'],
  supportedCountries: ['US'],
  environments: ['sandbox', 'production'],
  capabilities: {
    presentations: ['embedded', 'hosted', 'qr', 'none'],
    canResume: true,
    canRetry: true,
    canCancel: true,
    canRedact: true,
  },
  launcherKeys: ['persona_embedded', 'hosted'],
  launchPresentations: ['embedded', 'hosted', 'qr', 'none'],
  configurationSchemaVersion: 'urn:splitin:verification:config:persona:v1',
  configurationSchema: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    type: 'object',
    additionalProperties: false,
    required: [
      'apiKey',
      'environmentId',
      'idvTemplateId',
      'idvTemplateVersion',
      'associatedPersonTemplateId',
      'associatedPersonTemplateVersion',
      'kybTransactionTypeId',
      'kybWorkflowId',
      'kybWorkflowVersion',
      'caseTemplateId',
      'apiVersion',
      'webhookSecretCurrent',
    ],
    properties: {
      apiKey: secretStringProperty(),
      environmentId: plainStringProperty(),
      idvTemplateId: plainStringProperty(),
      idvTemplateVersion: plainStringProperty(),
      associatedPersonTemplateId: plainStringProperty(),
      associatedPersonTemplateVersion: plainStringProperty(),
      kybTransactionTypeId: plainStringProperty(),
      kybWorkflowId: plainStringProperty(),
      kybWorkflowVersion: plainStringProperty(),
      caseTemplateId: plainStringProperty(),
      caseType: plainStringProperty(),
      ownershipCaseType: { type: 'string', minLength: 1, 'x-secret': false },
      businessAuthorityCaseType: { type: 'string', minLength: 1, 'x-secret': false },
      kybCaseMode: { type: 'string', enum: ['workflow_managed', 'engine_managed'] },
      kybFieldMapJson: { type: 'string', minLength: 1, 'x-secret': false },
      statusMappingsJson: { type: 'string', minLength: 1, 'x-secret': false },
      apiVersion: { type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}$' },
      webhookSecretCurrent: secretStringProperty(),
      webhookSecretPrevious: { type: 'string', minLength: 1, 'x-secret': true },
      webhookToleranceSeconds: { type: 'integer', minimum: 60, maximum: 900 },
      allowedOrigins: { type: 'string', minLength: 1, 'x-secret': false },
    },
  },
  webhook: {
    protocol: 'persona_hmac_sha256',
    eventFamilies: ['inquiry', 'transaction', 'case', 'report', 'verification'],
    toleranceSeconds: 300,
  },
  dataPolicy: {
    classifications: ['provider_resource_id', 'normalized_status', 'reason_codes', 'evidence_reference'],
    prohibitedPersistence: ['raw_webhook', 'launch_secret', 'document', 'selfie', 'government_id'],
    rawPayloadPersistence: false,
    browserSecretPersistence: false,
    governmentIdentifierPersistence: false,
  },
  retry: { sameResourceWhenResumable: true, newAttemptAfterTerminal: true },
  cancellation: { supported: true, terminal: true },
  redaction: { supported: true, asynchronous: false },
  apiHosts: ['api.withpersona.com'],
  testedApiVersions: ['2023-01-05'],
});
