import { defineProviderManifest } from './manifest.ts';

const configurationString = (sensitive: boolean) => ({
  type: 'string' as const,
  minLength: 1,
  sensitive,
});

export const fakeProviderManifest = defineProviderManifest({
  contractVersion: '2.0.0',
  provider: 'test_fake',
  displayName: 'SplitIn Test Provider',
  adapterVersion: '2.0.0',
  supportedPackages: ['human_idv'],
  supportedCountries: ['US'],
  environments: ['sandbox'],
  capabilities: { presentations: ['embedded', 'hosted'], canResume: true, canRetry: true, canCancel: true, canRedact: true },
  launcherKeys: ['test_embedded', 'hosted'],
  requiredSecretNames: [],
  optionalSecretNames: [],
  configurationSchemaVersion: 'splitin.provider.test-fake.v2',
  webhook: { authentication: 'none', eventTypes: [] },
  dataPolicy: { prefillAllowlist: [], persistedDataClasses: ['normalized_status'], rawPayloadPersistence: false, browserSecretPersistence: false },
  retry: { sameResourceWhenResumable: true, newAttemptAfterTerminal: true },
});

export const plaidProviderManifest = defineProviderManifest({
  contractVersion: '2.0.0',
  provider: 'plaid',
  displayName: 'Plaid Identity Verification',
  adapterVersion: '2.0.0',
  supportedPackages: ['human_idv'],
  supportedCountries: ['US'],
  environments: ['sandbox', 'production'],
  capabilities: { presentations: ['embedded', 'hosted'], canResume: true, canRetry: true, canCancel: true, canRedact: false },
  launcherKeys: ['plaid_link', 'hosted'],
  requiredSecretNames: ['PLAID_CLIENT_ID'],
  optionalSecretNames: ['PLAID_PRODUCTION_SECRET', 'PLAID_SANDBOX_SECRET', 'PLAID_SECRET'],
  configurationSchemaVersion: 'splitin.provider.plaid-idv.v2',
  configurationSchema: {
    type: 'object',
    additionalProperties: false,
    required: ['PLAID_CLIENT_ID', 'PLAID_ENVIRONMENT'],
    properties: {
      PLAID_CLIENT_ID: configurationString(true),
      PLAID_PRODUCTION_SECRET: configurationString(true),
      PLAID_SANDBOX_SECRET: configurationString(true),
      PLAID_SECRET: configurationString(true),
      PLAID_ENVIRONMENT: configurationString(false),
      PLAID_CONFIG_REFERENCE: configurationString(false),
      PLAID_IDV_TEMPLATE_ID: configurationString(false),
      PLAID_SANDBOX_TEMPLATE_ID: configurationString(false),
      PLAID_TEMPLATE_ID: configurationString(false),
      PLAID_IDV_WEBHOOK_URL: configurationString(false),
    },
  },
  webhook: { authentication: 'plaid_es256_jwk', eventTypes: ['IDENTITY_VERIFICATION'] },
  dataPolicy: { prefillAllowlist: [], persistedDataClasses: ['provider_resource_id', 'normalized_status', 'reason_codes'], rawPayloadPersistence: false, browserSecretPersistence: false },
  retry: { sameResourceWhenResumable: true, newAttemptAfterTerminal: true },
});

export const personaProviderManifest = defineProviderManifest({
  contractVersion: '2.0.0',
  provider: 'persona',
  displayName: 'Persona',
  adapterVersion: '2.0.0',
  supportedPackages: ['human_idv', 'ownership_review', 'business_kyb', 'associated_person_idv'],
  supportedCountries: ['US'],
  environments: ['sandbox', 'production'],
  capabilities: { presentations: ['embedded', 'hosted', 'qr', 'none'], canResume: true, canRetry: true, canCancel: true, canRedact: true },
  launcherKeys: ['persona_embedded', 'hosted'],
  requiredSecretNames: ['PERSONA_API_KEY', 'PERSONA_WEBHOOK_SECRET_CURRENT'],
  optionalSecretNames: ['PERSONA_WEBHOOK_SECRET_PREVIOUS'],
  configurationSchemaVersion: 'splitin.provider.persona.v2',
  configurationSchema: {
    type: 'object',
    additionalProperties: false,
    required: [
      'PERSONA_ENVIRONMENT', 'PERSONA_CONFIG_REFERENCE', 'PERSONA_API_KEY',
      'PERSONA_ENVIRONMENT_ID', 'PERSONA_WEBHOOK_SECRET_CURRENT', 'PERSONA_API_VERSION',
      'PERSONA_IDV_TEMPLATE_ID', 'PERSONA_IDV_TEMPLATE_VERSION',
      'PERSONA_ASSOCIATED_PERSON_TEMPLATE_ID', 'PERSONA_ASSOCIATED_PERSON_TEMPLATE_VERSION',
      'PERSONA_KYB_TRANSACTION_TYPE_ID', 'PERSONA_KYB_WORKFLOW_ID', 'PERSONA_KYB_WORKFLOW_VERSION',
      'PERSONA_CASE_TEMPLATE_ID', 'PERSONA_CASE_TYPE', 'PERSONA_PROPERTY_OWNERSHIP_CASE_TYPE',
      'PERSONA_BUSINESS_AUTHORITY_CASE_TYPE', 'PERSONA_KYB_FIELD_MAP_JSON',
    ],
    properties: {
      PERSONA_ENVIRONMENT: configurationString(false),
      PERSONA_CONFIG_REFERENCE: configurationString(false),
      PERSONA_API_KEY: configurationString(true),
      PERSONA_ENVIRONMENT_ID: configurationString(false),
      PERSONA_WEBHOOK_SECRET_CURRENT: configurationString(true),
      PERSONA_WEBHOOK_SECRET_PREVIOUS: configurationString(true),
      PERSONA_WEBHOOK_TOLERANCE_SECONDS: configurationString(false),
      PERSONA_API_VERSION: configurationString(false),
      PERSONA_IDV_TEMPLATE_ID: configurationString(false),
      PERSONA_IDV_TEMPLATE_VERSION: configurationString(false),
      PERSONA_ASSOCIATED_PERSON_TEMPLATE_ID: configurationString(false),
      PERSONA_ASSOCIATED_PERSON_TEMPLATE_VERSION: configurationString(false),
      PERSONA_KYB_TRANSACTION_TYPE_ID: configurationString(false),
      PERSONA_KYB_WORKFLOW_ID: configurationString(false),
      PERSONA_KYB_WORKFLOW_VERSION: configurationString(false),
      PERSONA_CASE_TEMPLATE_ID: configurationString(false),
      PERSONA_CASE_TYPE: configurationString(false),
      PERSONA_PROPERTY_OWNERSHIP_CASE_TYPE: configurationString(false),
      PERSONA_BUSINESS_AUTHORITY_CASE_TYPE: configurationString(false),
      PERSONA_KYB_CASE_MODE: configurationString(false),
      PERSONA_KYB_FIELD_MAP_JSON: configurationString(false),
      PERSONA_STATUS_MAPPINGS_JSON: configurationString(false),
      PERSONA_ALLOWED_ORIGINS: configurationString(false),
    },
  },
  webhook: { authentication: 'persona_hmac_sha256', eventTypes: ['inquiry', 'transaction', 'case', 'report', 'verification'], toleranceSeconds: 300 },
  dataPolicy: { prefillAllowlist: ['legal_first_name', 'legal_last_name', 'email'], persistedDataClasses: ['provider_resource_id', 'normalized_status', 'reason_codes', 'evidence_reference'], rawPayloadPersistence: false, browserSecretPersistence: false },
  retry: { sameResourceWhenResumable: true, newAttemptAfterTerminal: true },
});

export const stripeIdentityProviderManifest = defineProviderManifest({
  contractVersion: '2.0.0',
  provider: 'stripe_identity',
  displayName: 'Stripe Identity',
  adapterVersion: '2.0.0',
  supportedPackages: ['human_idv'],
  supportedCountries: ['US'],
  environments: ['sandbox', 'production'],
  capabilities: { presentations: ['embedded', 'hosted'], canResume: true, canRetry: true, canCancel: true, canRedact: true },
  launcherKeys: ['stripe_identity', 'hosted'],
  requiredSecretNames: ['STRIPE_IDENTITY_RESTRICTED_KEY', 'STRIPE_IDENTITY_WEBHOOK_SECRET'],
  optionalSecretNames: ['STRIPE_IDENTITY_WEBHOOK_SECRET_PREVIOUS'],
  configurationSchemaVersion: 'splitin.provider.stripe-identity.v2',
  configurationSchema: {
    type: 'object',
    additionalProperties: false,
    required: [
      'STRIPE_IDENTITY_ENVIRONMENT', 'STRIPE_IDENTITY_RESTRICTED_KEY',
      'STRIPE_IDENTITY_WEBHOOK_SECRET', 'STRIPE_IDENTITY_API_VERSION',
      'STRIPE_IDENTITY_CONFIG_REFERENCE', 'STRIPE_IDENTITY_ACCOUNT_ID',
      'STRIPE_IDENTITY_RETURN_URL', 'STRIPE_IDENTITY_WEBHOOK_TOLERANCE_SECONDS',
    ],
    properties: {
      STRIPE_IDENTITY_ENVIRONMENT: configurationString(false),
      STRIPE_IDENTITY_RESTRICTED_KEY: configurationString(true),
      STRIPE_IDENTITY_WEBHOOK_SECRET: configurationString(true),
      STRIPE_IDENTITY_WEBHOOK_SECRET_PREVIOUS: configurationString(true),
      STRIPE_IDENTITY_WEBHOOK_TOLERANCE_SECONDS: configurationString(false),
      STRIPE_IDENTITY_API_VERSION: configurationString(false),
      STRIPE_IDENTITY_CONFIG_REFERENCE: configurationString(false),
      STRIPE_IDENTITY_ACCOUNT_ID: configurationString(false),
      STRIPE_IDENTITY_RETURN_URL: configurationString(false),
    },
  },
  webhook: {
    authentication: 'stripe_v1_hmac',
    eventTypes: [
      'identity.verification_session.processing',
      'identity.verification_session.verified',
      'identity.verification_session.requires_input',
      'identity.verification_session.canceled',
      'identity.verification_session.redacted',
    ],
    toleranceSeconds: 300,
  },
  dataPolicy: { prefillAllowlist: ['email'], persistedDataClasses: ['provider_resource_id', 'normalized_status', 'reason_codes'], rawPayloadPersistence: false, browserSecretPersistence: false },
  retry: { sameResourceWhenResumable: true, newAttemptAfterTerminal: true },
});

export const compiledProviderManifests = Object.freeze({
  test_fake: fakeProviderManifest,
  plaid: plaidProviderManifest,
  persona: personaProviderManifest,
  stripe_identity: stripeIdentityProviderManifest,
});

export type CompiledProviderCode = keyof typeof compiledProviderManifests;
